- p 187~ 191 groupby
- p 197 ~ 201 pivot

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [2]:
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [3]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [4]:
ser.sum()

np.float64(2.811925491708157)

In [5]:
ser.mean()

np.float64(0.5623850983416314)

In [6]:
df = pd.DataFrame({'A': rng.rand(5),
                    'B': rng.rand(5)})
df

          A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825

In [7]:
df.mean()

A    0.477888
B    0.443420
dtype: float64

In [8]:
df.mean(axis='columns')

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

In [9]:
planets.dropna().describe()

          number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [10]:
df = pd.DataFrame({'key':['A', 'B', 'C', 'A', 'B', 'C'],
                    'data': range(6)}, columns= ['key', 'data'])
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [11]:
df.groupby('key').sum()

     data
key
A       3
B       5
C       7

In [12]:
planets

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [13]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [14]:
for (method, group) in planets.groupby('method'):
    print("{0:30s} shape={1}".format(method, group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)

In [15]:
# select method, mean(year)
# from planets
# group by method

In [16]:
planets.groupby('method')['year'].mean()

method
Astrometry                       2011.500000
Eclipse Timing Variations        2010.000000
Imaging                          2009.131579
Microlensing                     2009.782609
Orbital Brightness Modulation    2011.666667
Pulsar Timing                    1998.400000
Pulsation Timing Variations      2007.000000
Radial Velocity                  2007.518987
Transit                          2011.236776
Transit Timing Variations        2012.500000
Name: year, dtype: float64

In [17]:
planets.groupby('method')['year'].describe().unstack()

       method
count  Astrometry                          2.0
       Eclipse Timing Variations           9.0
       Imaging                            38.0
       Microlensing                       23.0
       Orbital Brightness Modulation       3.0
                                         ...
max    Pulsar Timing                    2011.0
       Pulsation Timing Variations      2007.0
       Radial Velocity                  2014.0
       Transit                          2014.0
       Transit Timing Variations        2014.0
Length: 80, dtype: float64

- 집계

In [18]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key':['A', 'B', 'C', 'A', 'B', 'C'],
                    'data': range(6),
                    'data2': rng.randint(0,10,6)},
                    columns= ['key', 'data', 'data2'])

df

  key  data  data2
0   A     0      5
1   B     1      0
2   C     2      3
3   A     3      3
4   B     4      7
5   C     5      9

In [19]:
df.groupby('key').aggregate(['min', np.median, max])

C:\Users\user\AppData\Local\Temp\ipykernel_15120\968873422.py:1: FutureWarning: The provided callable <function median at 0x000002147E4E4550> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('key').aggregate(['min', np.median, max])
C:\Users\user\AppData\Local\Temp\ipykernel_15120\968873422.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('key').aggregate(['min', np.median, max])

    data            data2
     min median max   min median max
key
A      0    1.5   3     3    4.0   5
B      1    2.5   4     0    3.5   7
C      2    3.5   5     3    6.0   9

In [20]:
df.groupby('key').aggregate({'data': 'min',
                            'data2':'max'})

     data  data2
key
A       0      5
B       1      7
C       2      9

- 필터링

In [21]:
def filter_func(x):
    return x['data2'].std() > 4

print(df)
print(df.groupby('key').std())
print(df.groupby('key').filter(filter_func))

  key  data  data2
0   A     0      5
1   B     1      0
2   C     2      3
3   A     3      3
4   B     4      7
5   C     5      9
        data     data2
key
A    2.12132  1.414214
B    2.12132  4.949747
C    2.12132  4.242641
  key  data  data2
1   B     1      0
2   C     2      3
4   B     4      7
5   C     5      9

- 변환

1. 집계는 n개 들어가면 1개 나옴
2. 필터는 n개 들어가면 n개 나옴
3. 변환은 맵과 같다 n개 들어가서 n개 나옴 => 안의 데이터를 변환시킴

In [22]:
df.groupby('key').transform(lambda x: x - x.mean())

   data  data2
0  -1.5    1.0
1  -1.5   -3.5
2  -1.5   -3.0
3   1.5   -1.0
4   1.5    3.5
5   1.5    3.0

In [23]:
def norm_by_data2(x):
    x['data'] /= x['data2'].sum()
    return x

print(df)
print(df.groupby('key').apply(norm_by_data2))

  key  data  data2
0   A     0      5
1   B     1      0
2   C     2      3
3   A     3      3
4   B     4      7
5   C     5      9
      key      data  data2
key
A   0   A  0.000000      5
    3   A  0.375000      3
B   1   B  0.142857      0
    4   B  0.571429      7
C   2   C  0.166667      3
    5   C  0.416667      9

C:\Users\user\AppData\Local\Temp\ipykernel_15120\212210514.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  print(df.groupby('key').apply(norm_by_data2))

In [24]:
L = [0,1,0,1,2,0]
print(df)
print(df.groupby(L).sum())

  key  data  data2
0   A     0      5
1   B     1      0
2   C     2      3
3   A     3      3
4   B     4      7
5   C     5      9
   key  data  data2
0  ACC     7     17
1   BA     4      3
2    B     4      7

- 피벗 테이블

In [25]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [26]:
titanic.groupby('sex')[['survived']].mean()

        survived
sex
female  0.742038
male    0.188908

In [27]:
titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()

C:\Users\user\AppData\Local\Temp\ipykernel_15120\2603839867.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [28]:
titanic.pivot_table('survived', index='sex', columns='class')

C:\Users\user\AppData\Local\Temp\ipykernel_15120\1756680182.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('survived', index='sex', columns='class')

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [29]:
age = pd.cut(titanic['age'], [0,18,80]) # 아주 편한 방식, numpy bins랑 같음, 특이하게 왼쪽이 포함 안 되고 오른쪽은 포함됨 (...]
titanic.pivot_table('survived', ['sex', age],'class')

C:\Users\user\AppData\Local\Temp\ipykernel_15120\1582088738.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('survived', ['sex', age],'class')

class               First    Second     Third
sex    age
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [30]:
fare = pd.qcut(titanic['fare'], 2)
titanic.pivot_table('survived', ['sex', age], [fare, 'class'])

C:\Users\user\AppData\Local\Temp\ipykernel_15120\3929073192.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('survived', ['sex', age], [fare, 'class'])

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First
sex    age
female (0, 18]               NaN  1.000000  0.714286          0.909091
       (18, 80]              NaN  0.880000  0.444444          0.972973
male   (0, 18]               NaN  0.000000  0.260870          0.800000
       (18, 80]              0.0  0.098039  0.125000          0.391304

fare
class              Second     Third
sex    age
female (0, 18]   1.000000  0.318182
       (18, 80]  0.914286  0.391304
male   (0, 18]   0.818182  0.178571
       (18, 80]  0.030303  0.192308

- p 219 ~ datetime

In [31]:
import datetime as dt
dt.datetime(2021, 7, 4)

datetime.datetime(2021, 7, 4, 0, 0)

In [32]:
dt.datetime.today()

datetime.datetime(2025, 5, 12, 12, 51, 12, 278123)

In [33]:
dt.date.today()

datetime.date(2025, 5, 12)

In [34]:
dt.datetime.strptime('20250512', '%Y%m%d')

datetime.datetime(2025, 5, 12, 0, 0)

In [35]:
from dateutil import parser
date = parser.parse("4th of July, 2021")
date

datetime.datetime(2021, 7, 4, 0, 0)

In [36]:
date.strftime('%A')

'Sunday'

In [37]:
str(dt.date.today())

'2025-05-12'

In [38]:
dt.date.today().strftime('%Y-%m-%d')

'2025-05-12'

In [39]:
# 오늘로 부터 30일
# dt.date.today() + range(30) 은 안 됨

In [40]:
np.random.rand(64, 3, 32, 32).shape

(64, 3, 32, 32)

In [41]:
d = np.array(['2025-05-12'], np.datetime64)
d + np.arange(30)

array(['2025-05-12', '2025-05-13', '2025-05-14', '2025-05-15',
       '2025-05-16', '2025-05-17', '2025-05-18', '2025-05-19',
       '2025-05-20', '2025-05-21', '2025-05-22', '2025-05-23',
       '2025-05-24', '2025-05-25', '2025-05-26', '2025-05-27',
       '2025-05-28', '2025-05-29', '2025-05-30', '2025-05-31',
       '2025-06-01', '2025-06-02', '2025-06-03', '2025-06-04',
       '2025-06-05', '2025-06-06', '2025-06-07', '2025-06-08',
       '2025-06-09', '2025-06-10'], dtype='datetime64[D]')

In [42]:
d = np.array(['2025'], np.datetime64)
d + np.arange(30)

array(['2025', '2026', '2027', '2028', '2029', '2030', '2031', '2032',
       '2033', '2034', '2035', '2036', '2037', '2038', '2039', '2040',
       '2041', '2042', '2043', '2044', '2045', '2046', '2047', '2048',
       '2049', '2050', '2051', '2052', '2053', '2054'],
      dtype='datetime64[Y]')

In [43]:
d = np.array(['2025-05'], np.datetime64)
d + np.arange(30)

array(['2025-05', '2025-06', '2025-07', '2025-08', '2025-09', '2025-10',
       '2025-11', '2025-12', '2026-01', '2026-02', '2026-03', '2026-04',
       '2026-05', '2026-06', '2026-07', '2026-08', '2026-09', '2026-10',
       '2026-11', '2026-12', '2027-01', '2027-02', '2027-03', '2027-04',
       '2027-05', '2027-06', '2027-07', '2027-08', '2027-09', '2027-10'],
      dtype='datetime64[M]')

In [44]:
import pandas as pd
date = pd.to_datetime("4th of July, 2021")
date

Timestamp('2021-07-04 00:00:00')

In [45]:
date.strftime('%A')

'Sunday'

In [46]:
date + pd.to_timedelta(np.arange(12), 'D')

DatetimeIndex(['2021-07-04', '2021-07-05', '2021-07-06', '2021-07-07',
               '2021-07-08', '2021-07-09', '2021-07-10', '2021-07-11',
               '2021-07-12', '2021-07-13', '2021-07-14', '2021-07-15'],
              dtype='datetime64[ns]', freq=None)

1. 시간으로 인덱싱

In [47]:
index = pd.DatetimeIndex(['2020-07-04', '2020-08-04', '2021-07-04', '2021-08-04'])
data = pd.Series([0,1,2,3], index=index)
data

2020-07-04    0
2020-08-04    1
2021-07-04    2
2021-08-04    3
dtype: int64

In [48]:
data['2020-07-04':'2021-07-04']

2020-07-04    0
2020-08-04    1
2021-07-04    2
dtype: int64

In [49]:
data['2021']

2021-07-04    2
2021-08-04    3
dtype: int64

In [50]:
dates = pd.to_datetime([dt.datetime(2021, 7,3), '4th of July, 2021', '2021-Jul-6', '07-07-2021', '20210708'])
dates

DatetimeIndex(['2021-07-03', '2021-07-04', '2021-07-06', '2021-07-07',
               '2021-07-08'],
              dtype='datetime64[ns]', freq=None)

In [51]:
dates.to_period('D')

PeriodIndex(['2021-07-03', '2021-07-04', '2021-07-06', '2021-07-07',
             '2021-07-08'],
            dtype='period[D]')

In [52]:
dates - dates[0]

TimedeltaIndex(['0 days', '1 days', '3 days', '4 days', '5 days'], dtype='timedelta64[ns]', freq=None)

In [53]:
pd.date_range('2015-07-03', '2015-07-10')

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [54]:
pd.date_range('2015-07-03', periods=8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [55]:
pd.date_range('2015-07-03', periods=8, freq='H')

C:\Users\user\AppData\Local\Temp\ipykernel_15120\3521404607.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range('2015-07-03', periods=8, freq='H')

DatetimeIndex(['2015-07-03 00:00:00', '2015-07-03 01:00:00',
               '2015-07-03 02:00:00', '2015-07-03 03:00:00',
               '2015-07-03 04:00:00', '2015-07-03 05:00:00',
               '2015-07-03 06:00:00', '2015-07-03 07:00:00'],
              dtype='datetime64[ns]', freq='h')

In [56]:
pd.period_range('2015-07', periods=8, freq='M')

PeriodIndex(['2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12',
             '2016-01', '2016-02'],
            dtype='period[M]')

In [57]:
pd.timedelta_range(0, periods=10, freq='H')

C:\Users\user\AppData\Local\Temp\ipykernel_15120\3928887474.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.timedelta_range(0, periods=10, freq='H')

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00', '0 days 08:00:00',
                '0 days 09:00:00'],
               dtype='timedelta64[ns]', freq='h')

In [58]:
pd.timedelta_range(0, periods=9, freq='2H30T')

C:\Users\user\AppData\Local\Temp\ipykernel_15120\707367729.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.timedelta_range(0, periods=9, freq='2H30T')
C:\Users\user\AppData\Local\Temp\ipykernel_15120\707367729.py:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  pd.timedelta_range(0, periods=9, freq='2H30T')

TimedeltaIndex(['0 days 00:00:00', '0 days 02:30:00', '0 days 05:00:00',
                '0 days 07:30:00', '0 days 10:00:00', '0 days 12:30:00',
                '0 days 15:00:00', '0 days 17:30:00', '0 days 20:00:00'],
               dtype='timedelta64[ns]', freq='150min')

In [59]:
from pandas.tseries.offsets import BDay 
pd.date_range('2015-07-01', periods=5, freq=BDay()) # 영업일 오프셋

DatetimeIndex(['2015-07-01', '2015-07-02', '2015-07-03', '2015-07-06',
               '2015-07-07'],
              dtype='datetime64[ns]', freq='B')

In [62]:
from pandas_datareader import data
import yfinance as yf

yf.pdr_override()
sp500 = data.DataReader('^GSPC', start='2018-01-01', end='2021-12-31')
sp500.head()

TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn
seaborn.set()
sp500.plot()

In [ ]:
sp500.plot(alpha=0.5, style='-')
sp500.resample('BA').mean().plot(style=":")